sudo: false
language: go
os:
- linux
go:
- 1.11.1
script:
- gimme --list
- echo $TRAVIS_GO_VERSION
- cd dnscrypt-proxy
- go clean
- env CC=arm-linux-androideabi-clang CXX=arm-linux-androideabi-clang++
  CGO_ENABLED=1
  GOOS=android GOARCH=arm GOARM=7 go build -ldflags="-s -w"
- mkdir android-arm
- ln dnscrypt-proxy android-arm/
- cp ../LICENSE example-dnscrypt-proxy.toml example-*.txt android-arm/
- zip -9 -r dnscrypt-proxy-android_arm-${TRAVIS_TAG:-dev}.zip android-arm
- go clean
- env CC=aarch64-linux-android-clang CXX=aarch64-linux-android-clang++
  CGO_ENABLED=1
  GOOS=android GOARCH=arm64 go build -ldflags="-s -w"
- mkdir android-arm64
- ln dnscrypt-proxy android-arm64/
- cp ../LICENSE example-dnscrypt-proxy.toml example-*.txt android-arm64/
- zip -9 -r dnscrypt-proxy-android_arm64-${TRAVIS_TAG:-dev}.zip android-arm64
- go clean
- env CC=i686-linux-android-clang CXX=i686-linux-android-clang++
  CGO_ENABLED=1 GOOS=android
  GOARCH=386 go build -ldflags="-s -w"
- mkdir android-i386
- ln dnscrypt-proxy android-i386/
- cp ../LICENSE example-dnscrypt-proxy.toml example-*.txt android-i386/
- zip -9 -r dnscrypt-proxy-android_i386-${TRAVIS_TAG:-dev}.zip android-i386
- go clean
- env CC=x86_64-linux-android-clang CXX=x86_64-linux-android-clang++
  CGO_ENABLED=1
  GOOS=android GOARCH=amd64 go build -ldflags="-s -w"
- mkdir android-x86_64
- ln dnscrypt-proxy android-x86_64/
- cp ../LICENSE example-dnscrypt-proxy.toml example-*.txt android-x86_64/
- zip -9 -r dnscrypt-proxy-android_x86_64-${TRAVIS_TAG:-dev}.zip android-x86_64
- ls -l dnscrypt-proxy-*.zip
deploy:
  provider: releases
  api_key:
    secure: aha7ZoQ6xaT9uiWLgltCeUAWGjVkrRoKpnFmlirq+bZ7mGVLxYyB8TFKiC3id8Bji8x7pCsqdsKpeRZ4zSjmHioFv9zgZbkGxrpSuQ4Slx5HCwURsnZ7RfpY0yI4QqPx3ejYgCBqZXh2N0S+tZV833SNUhA9YfW+W5NO0l1hgOUifRTVGWIpgorODBx6q8eUi/3UvVXXaPGshjSjLWp3fQeCW8bjfaKYp6Nit1DX0BxEoOBzkunckUS/N0OoGT+Pwsae69NJWJmfVjt9go7XEP0C0yE+ayz4Ef0KcREUR4MyJISOIBvxHatiLKhquggJvFUvNwYuFq0MH2PYpJzxTxYc3ygqmygcu0FnsmHA12M2YYq829uYHCvMzHzXeGuIzFNerk/jPXX/GbWoP/vhedNKjX6Fpoy2gUlRc6D2spzehRh6bx+liGHiX6oQmNZKhsghLHTn2SvxofoAH++cQzOIrtn6i6NldcBbDvDRKXdmiH9HdEkPdbgBXn4YlXzHM/aeXNSPF+f4yYUX3X0unwQSWNhShzIMz31H2mTGgdtU+9j7hMcKgPVsYdMP7cNUdkqCIoL6BXUWtlHJaDsl3T1JmvzlORYOX7Jf6Zn9IN43P7l1/0SoGYJsrtNn+MglTDyTfBZKEgynHEtMSuxfGyAudBlQIjDWWIA5ISpvy7s=
  file:
  - dnscrypt-proxy-*.zip
  on:
    repo: sfionov/dnscrypt-proxy
    all_branches: true
after_deploy:
- ls -l dnscrypt-proxy-*.zip
before_install:
- NDK_VER=r18-beta2
- curl -LO http://dl.google.com/android/repository/android-ndk-${NDK_VER}-linux-x86_64.zip
- unzip -q android-ndk-${NDK_VER}-linux-x86_64.zip -d $HOME
- rm android-ndk-${NDK_VER}-linux-x86_64.zip
- NDK_TOOLS=$HOME/android-ndk-${NDK_VER}
- NDK_STANDALONE=$HOME/ndk-standalone-${NDK_VER}
- MAKE_TOOLCHAIN=$NDK_TOOLS/build/tools/make_standalone_toolchain.py
- for arch in x86 x86_64 arm arm64; do python $MAKE_TOOLCHAIN --arch $arch --api 21
  --install-dir $NDK_STANDALONE/$arch; PATH=$PATH:$NDK_STANDALONE/$arch/bin; done
- rm -rf $NDK_TOOLS
env:
  global:
  - secure: cuTXb4v5NwTr1XmkiHGkFir8fMiiBMnraCrls3thdDRlSTix0CiQc/H5Vh8SHauuG6VwVyrCT/Xsf0UQUmnULkPHjvuiNehb+bG4J3fz7hF94glBdQ8vxTuMmnHfJEYTQRLwCsWMBEC1wekw13O8J/0opFNG5neduns3Z1/rD5VSlBwgc8/4lomEp0fadIvzLeS7f5mxeXAD5Z9KBmc09uCjxVoF9Qsk1r901B0c0RMxIbJWyW9ZhDIVr/aEUN/tU0EXMKOA85sizg2moAigb8RZ1WCTh7utLGKpAyQegNk/unkksKMzZFkUCwHkrxlujwoe93wUS4rvZ+3nHMtLQdR+OfMeVs4/zvvQVq2f3bOXgkxgvhq6Bop0RK0xyEJffa5hUFbGNKhIFkLFLn1Ok28t2q7NOFPr0H2egHlkwgPztyhYMYb9C5PW4zd9buI0LS5452C4jXH5raBMfx844wTzaBbN689AKiYb84Qesqczss/o7eC7V48kh823dlZ/s2//gtp1ceqdAtNvp4dy7X/ECA/vNlpYisrtkR/CsFpJjGoTvS37leVMpmc5bn39dkoa5ZLliu7CaFRefbavcWWEImVStll9FBQ6+Ck9+41gczl9Rr7eGIV9ZZ/fmdkLNgxIpoAhZRee/dZD+/0gUExHxXXn10MqPuNVytVPiuU=
